---
title: "test script"
author: "nakada shunichi"
format:
  pdf:
    pdf-engine: lualatex
    keep-tex: false
    mainfont: "IPAexMincho"     # 日本語本文用明朝体
    sansfont: "IPAexGothic"     # 日本語本文のゴシック体（強調や見出しなどに自動切替）
    monofont: "IPAexGothic"     # コードチャンク等の等幅フォント
    mainfontoptions: "Scale=MatchLowercase,Ligatures=TeX"
    sansfontoptions: "Scale=MatchLowercase"
    monofontoptions: "Scale=MatchLowercase"
editor: 
  markdown: 
    wrap: 72
execute-dir: project
---

## 1. 共通データのセット

```{r}

rm(list = ls(all = TRUE))

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHS variables
library(labelled)   # used for Haven labeled variable creation
library(expss)      # for creating tables with Haven labeled data
library(rJava)      # required for xlsx package
library(naniar)     # to use replace_with_na function
library(here)       # to get R project path
library(fs)         # for file path manipulation
library(openxlsx) 　# for exporting to excel
library(purrr)      # for functional programming, e.g., map


# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）

# 対象とする年のリスト
yearlist <- c("2007", "2008", "2009", "2010", "2011",
"2012", "2013", "2014", "2015", "2016") 
# yearlist <- c("2015")
# my_year <- yearlist[8]

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# データベース一覧

endes_list <- readRDS(file.path(gdrive_dir, "output","endes_data_list.rds"))

# 変数ラベル一覧

endes_var_labels <- readRDS(file.path(gdrive_dir, "output", "endes_var_labels.rds"))

```

## 2. データ処理

```{r}
# 解析を実行する関数(各年ごとに実施)
go_analysis <- function(my_year){
  print(paste("Processing year:", my_year))
  
  # 6. 出力用のルートフォルダを指定
  output_dir <- file.path(gdrive_dir, "output", my_year) %>%
    normalizePath() %>%
    trimws() # 正規化してトリムする
  # 出力用のルートフォルダが存在しない場合は作成
  if (!dir_exists(output_dir)) {
    dir_create(output_dir)
  }
  
  # 7. 必要なデータセットの抽出
  print("必要なデータセットを抽出します")
  
  keep_rec0111 <- c("V005", "V008", "CASEID", "V001", "V002", "V000", "V003", 
                    "V013", "V022", "V025", "V026", "V024", "V106", "V190")
  keep_REC21 <- c("B3", "B4", "B5", "B9", "CASEID", "BIDX")
  keep_REC41 <- c("M4", "MIDX", "M34", "M38", "M39", "M55A", "M55B", "M55C", "M55D", 
                  "M55E", "M55F", "M55G", "M55H", "M55I", "M55J", "M55K", 
                  "M55L", "M55M", "M55N", "M55X", "M55Z", "CASEID", "MIDX")
  keep_REC42 <- c("V409", "V409A", "V410", "V410A", "V410B", "V410C", "V410D", 
                  "V411", "V411A", "V414A", "V414B", "V414C", "V414D", "V414E", 
                  "V414F", "V414G", "V414H", "V414I", "V414J", "V414K", "V414L", 
                  "V414M", "V414N", "V414O", "V414P", "V414Q", "V414R", "V414S", 
                  "V414T", "V414U", "V412", "V412A", "V412B", "V413", "V413A",
                  "V413A", "V413B", "V413C", "V413D", "CASEID")
  keep_REC43 <- c("H33M", "H33D", "H33Y", "H34", "H42", "CASEID", "HIDX")
  
  # addition for womens health status (IRdata)
  keep_rec0111_women <-c("V005", "V008", "V042")
  keep_RE223132_women <- c("CASEID","V208","V213")
  keep_REC21_women <- c("B3", "B9")
  keep_REC41_women <- c("M45", "M46", "M60")
  keep_REC42_women <- c("V438", "V445", "V455","V457")
  keep_IRdata <- c(keep_REC21_women, keep_REC41_women,keep_REC42_women,  
                   keep_rec0111_women, keep_RE223132_women)
  
  keep_rec0111 <- unique(c(keep_rec0111, keep_rec0111_women))
  keep_RE223132 <- keep_RE223132_women  
  keep_REC21 <- unique(c(keep_REC21, keep_REC21_women))
  keep_REC41 <- unique(c(keep_REC41, keep_REC41_women))
  keep_REC42 <- unique(c(keep_REC42, keep_REC42_women))
  
  df_rec0111 <- open_endes_file(my_year, "REC0111.SAV") %>%
    add_missing_columns(keep_rec0111) %>% dplyr::select(all_of(keep_rec0111))
  df_RE223132 <- open_endes_file(my_year, "RE223132.SAV") %>%
    add_missing_columns(keep_RE223132) %>% dplyr::select(all_of(keep_RE223132))
  df_REC21 <- open_endes_file(my_year, "REC21.sav") %>%
    add_missing_columns(keep_REC21) %>% dplyr::select(all_of(keep_REC21))
  df_REC41 <- open_endes_file(my_year, "REC41.SAV") %>%
    add_missing_columns(keep_REC41) %>% dplyr::select(all_of(keep_REC41))
  df_REC42 <- open_endes_file(my_year, "REC42.SAV") %>%
    add_missing_columns(keep_REC42) %>% dplyr::select(all_of(keep_REC42))
  df_REC43 <- open_endes_file(my_year, "REC43.SAV") %>%
    add_missing_columns(keep_REC43) %>% dplyr::select(all_of(keep_REC43))
  
  # 8. レコードの重複チェック(結合のため)
  print("レコードの重複チェックを行います")
  duplicate_check <- function(df, key_vars, df_name) {
    temp <- df %>%
      group_by(across(all_of(key_vars))) %>%
      summarise(n = n(), .groups = 'drop') %>%
      filter(n > 1)
    
    if (nrow(temp) > 0) {
      print(paste("重複レコードがあります in", df_name))
      print(temp)
      print(paste("レコード数：", nrow(df)))
    } else {
      print(paste("重複レコードはありません in", df_name))
      print(paste("レコード数：", nrow(df)))
    }
  }
  
  duplicate_check(df_REC21, c("CASEID", "BIDX"), "REC21.sav")
  duplicate_check(df_rec0111, c("CASEID"), "REC0111.SAV")
  duplicate_check(df_RE223132, c("CASEID"), "RE223132.SAV")
  duplicate_check(df_REC43, c("CASEID", "HIDX"), "REC43.SAV")
  duplicate_check(df_REC41, c("CASEID", "MIDX"), "REC41.SAV")
  duplicate_check(df_REC42, c("CASEID"), "REC42.SAV")
  
  # 9. データセットの結合(一番若い児童に限定)
  print("データセットを結合します")

  # 児童の健康関連指標
  KRdata <- df_REC21 %>% group_by(CASEID) %>% 
    filter(BIDX == 1) %>% ungroup() %>%   # 一番若い児童のBIDXを抽出
    inner_join_safe(df_rec0111, by = "CASEID") %>%
    inner_join_safe(df_REC43, by = c("CASEID", "BIDX" = "HIDX")) %>%
    inner_join_safe(df_REC41, by = c("CASEID", "BIDX" = "MIDX")) %>%
    inner_join_safe(df_REC42, by = "CASEID") %>%
    mutate(midx= BIDX)
  
  # 女性の健康状態関連指標
  IRdata <- df_REC21 %>% group_by(CASEID) %>% 
    filter(BIDX == 1) %>% ungroup() %>%   # 一番若い児童のBIDXを抽出
    inner_join_safe(df_rec0111, by = "CASEID") %>%
    inner_join_safe(df_RE223132, by = "CASEID") %>%
    inner_join_safe(df_REC43, by = c("CASEID", "BIDX" = "HIDX")) %>%
    inner_join_safe(df_REC41, by = c("CASEID", "BIDX" = "MIDX")) %>%
    inner_join_safe(df_REC42, by = "CASEID") %>%
    mutate(midx= BIDX) %>%
    dplyr::select(keep_IRdata)
  
  # 10. 列名の変更(大文字→小文字)
  KRdata <- KRdata %>%
    rename_with(tolower)
  IRdata <- IRdata %>%
    rename_with(tolower)
  
  # 11. 再度重複チェック
  duplicate_check(KRdata, c("caseid"), "KRdata")
  duplicate_check(IRdata, c("caseid"), "IRdata")
  
  print("データセットの結合が完了しました")
  print(paste("KRdataレコード数:", nrow(KRdata)))
  print(paste("IRdataレコード数:", nrow(IRdata)))
  
  # 12. Calculate age of child. use v008 - b3
  KRdata <- KRdata %>%
    mutate(
      age = v008 - b3,
      wt = v005 / 1000000
    )
  IRdata <- IRdata %>%
    mutate(
      age = v008 - b3,
      wt = v005 / 1000000
    )
  print("wtおよび年齢変数を追加しました")
  
  # 13. 月齢24ヶ月未満の子供に制限
  #create subset of KRfile to select for children for IYCF indicators
  KRdata <- KRdata %>%
    filter(age < 24 & b9==0)
  IRdata <- IRdata %>%
    filter(age < 24 & b9==0)
  print("月齢24ヶ月未満の子供に制限しました")
  print(paste("KRdataレコード数:", nrow(KRdata)))
  print(paste("IRdataレコード数:", nrow(IRdata)))  
  
  chap <- "Chap11_NT"
  
  # 14. 各種の指標計算(NT_CH_MICRO)
  source(here(paste0(chap,"/NT_CH_MICRO.R")), local = environment())
  # Purpose: 	Code micronutrient indicators
  
  
  # 15. 各種の指標計算(NT_BF_INIT)
  source(here(paste0(chap,"/NT_BF_INIT.R")), local = environment())
  # Purpose:   Code initial breastfeeding indicators
  
  # 16. 各種の指標計算(NT_WM_NT)
  source(here(paste0(chap,"/NT_WM_NUT.R")), local = environment())
  # Purpose: 	Code women's anthropometric indicators

    
  # 17.オリジナルのコードに合わせるためデータファイルの名称変更
  KRiycf <- KRdata  # IYCF indicators are calculated on KRdata
  
  # 18. 各種の指標計算(NT_IYCF)
  source(here(paste0(chap,"/NT_IYCF.R")), local = environment())
  # Purpose: 			Code to compute infant and child feeding indicators

    
  # 19. 年をデータフレームに追加
  KRiycf <- KRiycf %>%
    mutate(year = my_year)
  IRdata <- IRdata %>%
    mutate(year = my_year)
  print("add year variable")
  
  # 20. 出力用の変数を指定
  vars_to_keep <- KRiycf %>%
    dplyr::select(starts_with("nt")) %>%
    names() %>%
    append(c("year", "caseid", "age", "v001", "v002", "v003", "v005", "v013", "v022", 
             "v025", "v026", "b4", "v024", "v106", "v190")) # add the variables we need to keep
  
  # print(vars_to_keep)
  
  vars_to_keep_IR<- IRdata %>%
    dplyr::select(starts_with("nt")) %>%
    names() %>%
    append(c("year", "caseid")) # add the variables we need to keep
  print(vars_to_keep_IR)

  # 順序を保って選択
  KRiycf <- KRiycf[, vars_to_keep]
  IRdata <- IRdata[, vars_to_keep_IR]
  
  # 21. KRiycfをoutput folderにdta形式で保存
  print("save KRiycf into output folder")
  saveRDS(KRiycf, paste0(output_dir, "/KRiycf-nt.rds"))
  print("complete KRiycf into output folder")
  
  print("save IRdata into output folder")
  saveRDS(IRdata, paste0(output_dir, "/IRdata-nt.rds"))
  print("complete IRdata into output folder")
} 

```

## 3. テスト用2

```{r}
for (my_year in yearlist) {
  go_analysis(my_year)
}

print("All done!")
```

## Compare this snippet from Chap02_PH/DHS8/PH_GINI.R:
