---
title: "test script"
author: "nakada shunichi"
format:
  pdf:
    pdf-engine: lualatex
    keep-tex: false
    mainfont: "IPAexMincho"     # 日本語本文用明朝体
    sansfont: "IPAexGothic"     # 日本語本文のゴシック体（強調や見出しなどに自動切替）
    monofont: "IPAexGothic"     # コードチャンク等の等幅フォント
    mainfontoptions: "Scale=MatchLowercase,Ligatures=TeX"
    sansfontoptions: "Scale=MatchLowercase"
    monofontoptions: "Scale=MatchLowercase"
editor: 
  markdown: 
    wrap: 72
execute-dir: project
---

## 1. 共通データのセット

```{r}

rm(list = ls(all = TRUE))

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHS variables
library(labelled)   # used for Haven labeled variable creation
library(expss)      # for creating tables with Haven labeled data
library(rJava)      # required for xlsx package
library(naniar)     # to use replace_with_na function
library(here)       # to get R project path
library(fs)         # for file path manipulation
library(openxlsx) 　# for exporting to excel
library(survey)       # for survey design


# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）
source("_tool_safe_join.R")  # 安全な結合関数
source("_tool_SaveLabel.R")  # 変数ラベル保存関数

# 対象とする年のリスト
yearlist <- c("2005", "2006", "2007", "2008", "2009", "2010", "2011",
"2012", "2013", "2014", "2015", "2016")
# yearlist <- c("2006")

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# データベース一覧

endes_list <- readRDS(file.path(gdrive_dir, "output","endes_data_list.rds"))

# 変数ラベル一覧

endes_var_labels <- readRDS(file.path(gdrive_dir, "output", "endes_var_labels.rds"))

```

## 2. データ処理

```{r}
# 必要なデータセットの抽出

# ソースコードのルートフォルダを指定
chap <- "Chap09_RH"

goAnalysis <- function(year){
  
  # 母親の雇用状態を追加
  keep_REC21 <- c("b3", "b4", "b5", "b9", "caseid", "bidx")
  keep_rec0111 <- c("caseid", "v005", "v008", "v012", "v021", "v022", "v025", 
                    "v106", "v190")
  keep_rec41 <- c("caseid", "midx", "m1", "m1d", "m2a", "m2b", "m2c", "m2d", 
                  "m2e", "m2f", "m2g", "m2h", "m2i", "m2j", "m2k", "m2l", 
                  "m2m", "m3a", "m3b", "m3c", "m3d", "m3e", "m3f", "m3g", 
                  "m3h", "m3i", "m3j", "m3k", "m3l", "m3m", "m3n",
                  "m13", "m14", "m15", "m17", "m42c", "m42d", "m42e", "m43", 
                  "m45", "m60", "m61")
  keep_RE223132 <-c("caseid", "v208")
  keep_REC42 <- c("caseid", "v467b","v467c","v467d", "v467f")
  
  # 2005年はファイル名が違うため設定
  myname_RE223132 <- ifelse(year == "2005", "REC22312.SAV", "RE223132.SAV")
  
  # 設定した年に基づいてファイルを読み込む
  df_REC21 <- open_endes_file(year, "REC21.sav") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_REC21) %>% select(all_of(keep_REC21))
  df_rec0111 <- open_endes_file(year, "REC0111.SAV") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_rec0111) %>% select(all_of(keep_rec0111))
  df_rec41 <- open_endes_file(year, "REC41.SAV") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_rec41) %>% select(all_of(keep_rec41))
  df_RE223132 <- open_endes_file(year, myname_RE223132) %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_RE223132) %>% select(all_of(keep_RE223132))
  
  df_REC42 <- open_endes_file(year, "REC42.SAV") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_REC42) %>% select(all_of(keep_REC42))

  labels_df_REC21 <- endes_var_labels[[year]][["REC21.sav"]]
  # *************************************************************************  
  #2005/2006年の場合はv022の値がおかしいので別途用意
  if (year %in% c("2005")) {
    key_v022_2005 <- read_sav(file.path(gdrive_dir, "/2005_DHS/KR/PEKR51FL.SAV"))  %>%
      rename_with(~ tolower(.x)) %>%
      distinct(caseid, v022)
  }
  if (year %in% c("2006")) {
    key_v022_2006 <- read_sav(file.path(gdrive_dir, "2006/183-Modulo64/RECH0.SAV")) %>%
      rename_with(~ tolower(.x)) %>%
      rename(
        v021 = hv021,
        v022 = hv022
        ) %>%
      distinct(hhid, v022)
  }
  # *************************************************************************  
  
  # 重複チェック
  duplicate_check(df_rec0111, "caseid", "df_rec0111")
  duplicate_check(df_REC21, c("caseid", "bidx"), "REC21")
  # duplicate_check(df_rec41, c("caseid", "midx"), "df_rec41")
  # duplicate_check(df_RE223132, "caseid", "df_RE223132")
  # duplicate_check(df_REC42, "caseid", "df_REC42")

  print("データセットを結合します")
  IRdata <- df_REC21 %>% group_by(caseid) %>% 
    filter(bidx == 1) %>% ungroup() %>%   # 一番若い児童のBIDXを抽出
    inner_join(df_rec0111, by = "caseid") %>%
    left_join_safe(
      df_rec41, by = c("caseid" = "caseid", "bidx" = "midx"), 
      diagnose = TRUE) %>%
    left_join_safe(
      df_RE223132, by = "caseid", diagnose = TRUE) %>%
    left_join_safe(
      df_REC42, by = "caseid", diagnose = TRUE)
  
  # データセットの結合後に年の変数を追加
  IRdata <- IRdata %>%
  mutate(year = year)

  print("データセットの結合が完了しました")
  print(paste("レコード数:", nrow(IRdata)))

  # *************************************************************************  
  # 2005年データのv021, v022を確認
  if (year %in% c("2005")){
    print("2005年データのv021, v022を更新します")
    IRdata <- IRdata %>%
      left_join_safe(key_v022_2005, by = "caseid", 
                     priotiry_col_left = FALSE, diagnose = TRUE)
  }
  if (year %in% c("2006")) {
    # caseidとhhidをマッチさせるため少し複雑
    print("2006年データのv021, v022を確認します")
    # キーの正規化と結合キーの作成
    IRdata <- IRdata %>%
      mutate(
        join_key = paste(
          word(str_trim(str_squish(caseid)), 1),
          word(str_trim(str_squish(caseid)), 2)
        )
      )

    key_v022_2006 <- key_v022_2006 %>%
      mutate(
        join_key = paste(
          word(str_trim(str_squish(hhid)), 1),
          word(str_trim(str_squish(hhid)), 2)
        )
      )
    IRdata <- IRdata %>%
      left_join_safe(
        key_v022_2006,
        by = "join_key",
        diagnose = TRUE
      ) %>%
    select(-join_key)
  }  
  # *************************************************************************  

  # 子供の年齢確認 v008 - b3
  IRdata <- IRdata %>%
    mutate(
      age = v008 - b3,
      wt = v005 / 1000000
    )
  print("wtおよび年齢変数を追加しました")
  
  # 13. 月齢24ヶ月未満の子供に制限
  #create subset of KRfile to select for children for IYCF indicators
  IRdata <- IRdata %>%
    filter(age < 24 & b9==0)
  print("月齢24ヶ月未満の子供に制限しました")
  duplicate_check(IRdata, "caseid", "IRdata")
  print(paste("レコード数:", nrow(IRdata)))
  
  #ラベル情報の保存と削除
  # labels_IR <- save_labels_to_memory(IRdata)
  # IRdata <- remove_labels(IRdata)
  
  # あとで使うためにBRdataを用意
  BRdata <- IRdata

  # create analytic variables
  source(here(paste0(chap,"/RH_ANC.R")), local = environment())
  # Purpose: 	Code ANC indicators

  source(here(paste0(chap,"/RH_Probs.R")), local = environment())
  # Purpose: 	Code indicators for problems accessing health care 

  IRdata <- IRdata %>%
    mutate(year = year)
  
  vars_to_keep <- IRdata %>%
    select(starts_with("rh")) %>%
    names() %>%
    append(c("year", "caseid", "age", "wt")) # add the variables we need to keep
  
  # print(vars_to_keep)
  # 順序を保って選択
  
  IRdata <- IRdata[, vars_to_keep]

  # 変数ラベルを復元
  # IRdata <- restore_labels_from_memory(IRdata, labels_IR)
  
  # 出力用のルートフォルダを指定
  output_dir <- file.path(gdrive_dir, "output", year) %>%
    normalizePath() %>%
    trimws() # 正規化してトリムする
  # 出力用のルートフォルダが存在しない場合は作成
  if (!dir_exists(output_dir)) {
    dir_create(output_dir)
  }
  
  # IRdata folderにrds形式で保存
  print(sprintf("save IRdata into output folder for %s", year))
  saveRDS(IRdata, paste0(output_dir, "/IRdata-rh.rds"))
  print("complete IRdata into output folder")
  
  # 出産時のケアに関する指標
  source(here(paste0(chap,"/RH_DEL.R")), local = environment())
  # Purpose: 	Code indicators for problems accessing health care
  
  vars_to_keep <- BRdata %>%
    select(starts_with("rh_")) %>%
    names() %>%
    append(c("year", "caseid")) # add the variables we need to keep

  BRdata <- BRdata[, vars_to_keep]
  
  # 出力データにどれくらいNA値が含まれるか
  print("***************************************************************")
  cat("Missing values in BRdata RH variables: ",year, "\n")
  print(sapply(c("rh_del_place","rh_del_pltype","rh_del_pv","rh_del_pvskill","rh_del_ces", "rh_del_cestime"), function(x) {
    sum(is.na(BRdata[[x]]))
  }))
  print("***************************************************************")
  
  
  # BRdata folderにrds形式で保存
  print(sprintf("save BRdata into output folder for %s", year))
  saveRDS(BRdata, paste0(output_dir, "/BRdata-rh.rds"))
  print("complete BRData into output folder")
    
}

```

## 3. ループ実行

```{r}
#** ここから実行
for (yr in yearlist) {
  goAnalysis(yr)
}
```

