---
title: "test script"
author: "nakada shunichi"
format:
  pdf:
    pdf-engine: lualatex
    keep-tex: false
    mainfont: "IPAexMincho"     # 日本語本文用明朝体
    sansfont: "IPAexGothic"     # 日本語本文のゴシック体（強調や見出しなどに自動切替）
    monofont: "IPAexGothic"     # コードチャンク等の等幅フォント
    mainfontoptions: "Scale=MatchLowercase,Ligatures=TeX"
    sansfontoptions: "Scale=MatchLowercase"
    monofontoptions: "Scale=MatchLowercase"
editor: 
  markdown: 
    wrap: 72
execute-dir: project
---

## 1. 共通データのセット

```{r}

rm(list = ls(all = TRUE))

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHS variables
library(labelled)   # used for Haven labeled variable creation
library(expss)      # for creating tables with Haven labeled data
library(rJava)      # required for xlsx package
library(naniar)     # to use replace_with_na function
library(here)       # to get R project path
library(fs)         # for file path manipulation
library(openxlsx) 　# for exporting to excel
library(survey)       # for survey design


# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）

# 対象とする年のリスト
yearlist <- c("2005", "2006", "2007", "2008", "2009", "2010", "2011",
"2012", "2013", "2014", "2015", "2016")
# yearlist <- c("2005", "2006")
# my_year <- yearlist[8]

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# データベース一覧

endes_list <- readRDS(file.path(gdrive_dir, "output","endes_data_list.rds"))

# 変数ラベル一覧

endes_var_labels <- readRDS(file.path(gdrive_dir, "output", "endes_var_labels.rds"))

```

## 2. データ処理

```{r}
# 必要なデータセットの抽出

# ソースコードのルートフォルダを指定
chap <- "Chap10_CH"

goAnalysis <- function(year){
  # 出力用のルートフォルダを指定
  output_dir <- file.path(gdrive_dir, "output", year) %>%
    normalizePath() %>%
    trimws() # 正規化してトリムする
  # 出力用のルートフォルダが存在しない場合は作成
  if (!dir_exists(output_dir)) {
    dir_create(output_dir)
  }
  
  # 母親の雇用状態を追加
  keep_rec41 <- c("caseid", "midx", "m18", "m19")
  keep_rec43 <- c("caseid", "hidx", "h0", "h1", "h2", "h3", "h4", "h5", "h6", "h7", 
                  "h8", "h9",
                  "h11","h12a", "h12b", "h12c", "h12d", "h12e", 
                  "h12f", "h12g", "h12h", "h12i", "h12j", "h12k", "h12l", "h12m", 
                  "h12n", "h12o", "h12p", "h12q", "h12r", "h12s", "h12t", "h12u", 
                  "h12v", "h12w", "h12x", "h12y", "h12z","h13", "h13b", "h14",
                  "h15", "h15a", "h15b", "h15c", "h15d", "h15e", "h15f", "h15g", 
                  "h15h", "h15i", "h15j", "h15k", "h15l", "h15m",
                  "h22", "h31", "h31b", "h31c", "h32a", "h32b", 
                  "h32c", "h32d", "h32e", "h32f", "h32g", "h32h", "h32i", "h32j", 
                  "h32k", "h32l", "h32m", "h32n", "h32o", "h32p", "h32q", 
                  "h32r", "h32s", "h32t", "h32u", "h32v", "h32w", "h32x", "h38",
                  "h39",
                  "h46b")
  keep_REC21 <- c("b3", "b5", "b9", "caseid", "bidx")
  keep_rec0111 <- c("caseid", "v005", "v008")
  # keep_RE223132 <-c("caseid", "v208")
  keep_REC42 <- c("caseid", "v465")
  
  # 設定した年に基づいてファイルを読み込む
  df_REC21 <- open_endes_file(year, "REC21.sav") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_REC21) %>% select(all_of(keep_REC21))
  df_rec41 <- open_endes_file(year, "REC41.SAV") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_rec41) %>% select(all_of(keep_rec41))
  df_REC43 <- open_endes_file(year, "REC43.sav") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_rec43) %>% select(all_of(keep_rec43))
  df_rec0111 <- open_endes_file(year, "REC0111.SAV") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_rec0111) %>% select(all_of(keep_rec0111))
  df_REC42 <- open_endes_file(year, "REC42.sav") %>%
    rename_with(~ tolower(.x)) %>% # 変数名を小文字に変換
    add_missing_columns(keep_REC42) %>% select(all_of(keep_REC42))

  # 重複チェック
  duplicate_check(df_REC21, c("caseid", "bidx"), "REC21")
  duplicate_check(df_rec41, c("caseid", "midx"), "df_rec41")
  duplicate_check(df_REC43, c("caseid", "hidx"), "df_REC43")
  duplicate_check(df_rec0111, "caseid", "df_rec0111")
  duplicate_check(df_REC42, "caseid", "df_REC42")

  print("データセットを結合します")
  KRdata <- df_REC21 %>% group_by(caseid) %>% 
    filter(bidx == 1) %>% ungroup() %>%   # 一番若い児童のBIDXを抽出
    left_join(df_rec41, by = c("caseid" = "caseid", "bidx" = "midx")) %>%
    left_join(df_REC43, by = c("caseid" = "caseid", "bidx" = "hidx")) %>%
    left_join(df_rec0111, by = c("caseid" = "caseid")) %>%
    left_join(df_REC42, by = c("caseid" = "caseid")) %>%
    mutate(year = year)

  print("データセットの結合が完了しました")
  print(paste("レコード数:", nrow(KRdata)))

  # 子供の年齢確認 v008 - b3
  KRdata <- KRdata %>%
    mutate(
      age = v008 - b3,
      wt = v005 / 1000000
    )
  print("wtおよび年齢変数を追加しました")
  
  # 13. 月齢24ヶ月未満の子供に制限
  #create subset of KRfile to select for children for IYCF indicators
  KRdata_org <- KRdata %>%
    filter(age < 24 & b9==0)
  print("月齢24ヶ月未満の子供に制限しました")
  duplicate_check(KRdata, "caseid", "KRdata")
  print(paste("レコード数:", nrow(KRdata)))
      
  # 14. ここから実際のデータ処理(1)
  # KRdataの初期設定
  KRdata <- KRdata_org
  # create analytic variables
  source(here(paste0(chap,"/CH_SIZE.R")), local = environment())
  # Purpose: 	Code child size indicators
  
  # データ処理の実施
  source(here(paste0(chap,"/CH_ARI_FV.R")), local = environment())
  # Purpose:	Code ARI indicators
  
  # 最終データ項目を選択
  vars_to_keep <- KRdata %>%
    select(starts_with("ch")) %>%
    names() %>%
    append(c("year", "caseid", "age", "wt")) # add the variables we need to keep
  KRdata <- KRdata[, vars_to_keep]

  # KRdata folderにrds形式で保存
  print(sprintf("save KRdata into output folder for %s", year))
  print("KRdata")
  saveRDS(KRdata, paste0(output_dir, "/KRdata.rds"))
  
  # 15. ここから実際のデータ処理(2)
  # KRdataの初期設定
  KRdata <- KRdata_org
  
  source(here(paste0(chap,"/CH_VAC.R")), local = environment())
  # Purpose:	Code vaccination indicators
  # Note:     This code will create a data subset KRvac for children in the vaccination age group

  # 最終データ項目を選択
  vars_to_keep2 <- KRvac %>%
    select(starts_with("ch")) %>%
    names() %>%
    append(c("year", "caseid", "age", "wt")) # add the variables we need to keep
  KRvac <- KRvac[, vars_to_keep2]

  # KRdata folderにrds形式で保存
  print("KRvac")
  saveRDS(KRvac, paste0(output_dir, "/KRvac.rds"))

  # 16. ここから実際のデータ処理(3)
  # KRdataの初期設定
  KRdata <- KRdata_org  
  
  source(here(paste0(chap,"/CH_STOOL.R")), local = environment())
  # Purpose:	Safe disposal of stool
  # Note:     This code will create a data subset KRstool to selected for youngest child under age 2 living with the mother

  # 最終データ項目を選択
  vars_to_keep3 <- KRstool %>%
    select(starts_with("ch")) %>%
    names() %>%
    append(c("year", "caseid", "age", "wt")) # add the variables we need to keep
  KRstool <- KRstool[, vars_to_keep3]
  
  # KRdata folderにrds形式で保存
  print("KRstool")
  saveRDS(KRstool, paste0(output_dir, "/KRstool.rds"))
  print("complete KRdata into output folder")
  
}

```

## 3. ループ実行

```{r}
#** ここから実行
for (yr in yearlist) {
  goAnalysis(yr)
}
```

## Compare this snippet from Chap02_PH/DHS8/PH_GINI.R:
