---
title: "test script"
author: "nakada shunichi"
format:
  pdf:
    pdf-engine: lualatex
    keep-tex: false
    mainfont: "IPAexMincho"     # 日本語本文用明朝体
    sansfont: "IPAexGothic"     # 日本語本文のゴシック体（強調や見出しなどに自動切替）
    monofont: "IPAexGothic"     # コードチャンク等の等幅フォント
    mainfontoptions: "Scale=MatchLowercase,Ligatures=TeX"
    sansfontoptions: "Scale=MatchLowercase"
    monofontoptions: "Scale=MatchLowercase"
editor: 
  markdown: 
    wrap: 72
execute-dir: project
---


## 1. 共通データのセット

```{r}

rm(list = ls(all = TRUE))

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHS variables
library(labelled)   # used for Haven labeled variable creation
library(expss)      # for creating tables with Haven labeled data
library(rJava)      # required for xlsx package
library(naniar)     # to use replace_with_na function
library(here)       # to get R project path
library(fs)         # for file path manipulation
library(openxlsx) 　# for exporting to excel
library(survey)       # for survey design


# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）

# 対象とする年のリスト
yearlist <- c("2007", "2008", "2009", "2010", "2011",
"2012", "2013", "2014", "2015", "2016")
yearlist <- c("2005")

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# データベース一覧

endes_list <- readRDS(file.path(gdrive_dir, "output","endes_data_list.rds"))

# 変数ラベル一覧

endes_var_labels <- readRDS(file.path(gdrive_dir, "output", "endes_var_labels.rds"))

```

## 2. データ処理

```{r}
# 必要なデータセットの抽出

# ソースコードのルートフォルダを指定
chap <- "Chap02_PH"

  
goAnalysis <- function(year){
  cat("DHSデータの確認を行います\n")
  HRdata <- read_spss("/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss/2005_DHS/HR/PEHR51FL.SAV") %>%
    rename_with(~ tolower(.x))  # すべての列名を小文字に変換
  
  cat("PH_HOUS.Rを実行\n")
  source(here(paste0(chap,"/PH_HOUS.R")), local = environment())
  # Purpose:	Code housing indicators such as house material, assets, cooking fuel and place, and smoking in the home
  
  cat("PH_SANI.Rを実行\n")
  WASHdata <- HRdata %>% 
    mutate(ph_sani_type = hv205)
  source(here(paste0(chap,"/PH_SANI.R")), local = environment())
  # Purpose: 	Code Sanitation indicators
  
  cat("PH_WATER.Rを実行")
  source(here(paste0(chap,"/PH_WATER.R")), local = environment())
  # Purpose: 	Code Water Source indicators
  
  cat("WASHdataから必要な変数を抽出")
  # WASHdataから必要な変数を選択
  vars_to_keep <- WASHdata %>%
    dplyr::select(starts_with("ph")) %>%
    names() %>%
    append(c("hhid")) # add the variables we need to keep
      
  WASHdata <- WASHdata[, vars_to_keep]

  # 出力用のルートフォルダを指定
  output_dir <- file.path(gdrive_dir, "output", year) %>%
    normalizePath() %>%
    trimws() # 正規化してトリムする
  # 出力用のルートフォルダが存在しない場合は作成
  if (!dir_exists(output_dir)) {
    dir_create(output_dir)
  }
  
  # WASHdata folderにrds形式で保存
  print(sprintf("save WASHdata into output folder for %s", year))
  print("WASHdata")
  saveRDS(WASHdata, paste0(output_dir, "/WASHdata-ws.rds"))
  print("complete WASHdata into output folder")
  
}

```

## 3. ループ実行

```{r}
#** ここから実行
for (yr in yearlist) {
  goAnalysis(yr)
}
```

## Compare this snippet from Chap02_PH/DHS8/PH_GINI.R:
