---
title: "test script"
author: "nakada shunichi"
format:
  pdf:
    pdf-engine: lualatex
    keep-tex: false
    mainfont: "IPAexMincho"     # 日本語本文用明朝体
    sansfont: "IPAexGothic"     # 日本語本文のゴシック体（強調や見出しなどに自動切替）
    monofont: "IPAexGothic"     # コードチャンク等の等幅フォント
    mainfontoptions: "Scale=MatchLowercase,Ligatures=TeX"
    sansfontoptions: "Scale=MatchLowercase"
    monofontoptions: "Scale=MatchLowercase"
editor: 
  markdown: 
    wrap: 72
execute-dir: project
---

## 1. 共通データのセット

```{r}

rm(list = ls(all = TRUE))

# デバッグモードフラグ
debug_mode = TRUE  # デバッグモード
# debug_mode = FALSE # 通常モード

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHS variables
library(labelled)   # used for Haven labeled variable creation
library(expss)      # for creating tables with Haven labeled data
library(rJava)      # required for xlsx package
library(naniar)     # to use replace_with_na function
library(here)       # to get R project path
library(fs)         # for file path manipulation
library(openxlsx) 　# for exporting to excel
library(survey)       # for survey design


# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）

# 対象とする年のリスト
yearlist <- c("2007", "2008", "2009", "2010", "2011",
"2012", "2013", "2014", "2015", "2016")
# yearlist <- c("2015")
# my_year <- yearlist[8]

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# ENAHOデータのルートフォルダ指定
gdrive_enaho_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_enaho/output"


# データベース一覧

endes_list <- readRDS(file.path(gdrive_dir, "output","endes_data_list.rds"))

# 変数ラベル一覧

endes_var_labels <- readRDS(file.path(gdrive_dir, "output", "endes_var_labels.rds"))

```

## 2. データ処理

```{r}

library(sjmisc)  # add_rowsのために追加
all_data_merged <- NULL   # 空のリストまたはデータフレームとして初期化

# 各年ごとのデータセットを読み込み、結合
for (yr in yearlist) {
  root_folder <- file.path(gdrive_dir, "output", yr) %>%
    normalizePath() %>%
    trimws()
  year_data <- read_rds(file.path(root_folder, "data_merged.rds")) %>%
    filter(!is.na(hhid))

  print(paste("Processing year:", yr, "with", nrow(year_data), "records"))
  # bind_rowsの代わりにadd_rowsを使用
  all_data_merged <- add_rows(all_data_merged, year_data) %>%
    as_tibble()
  print(paste("Total records so far:", nrow(all_data_merged)))
  
  # if (debug_mode) {
  #   if ("rc_edu_acceptable" %in% names(year_data)) {
  #     print(paste("year_data: ", get_label(year_data$rc_edu_acceptable)))
  #     print(paste("all_data: ", get_label("all_data: ",all_data_merged$rc_edu_acceptable)))
  #   } else {
  #     stop(paste("failed in year", yr, ": 'rc_edu_acceptable' not found"))
  #   }
  # }
}

duplicate_check(all_data_merged, c("year", "caseid"), "all_data_merged")

# 分析用の共通変数の読み込み
endes_keys <- read_rds(file.path(gdrive_dir, "output", "endes_keys.rds")) %>%
  dplyr::select(-c(v026, v024, v005, v021, v022, v025, v001, v002, v003))

# 共通キーでマージ
all_data_merged <- all_data_merged %>%
  left_join_safe(endes_keys, c("year", "hhid"))

# 重複チェック
duplicate_check(all_data_merged, c("year", "caseid"), "all_data_merged")


# ******************************************************************************
# 食品摂取量データの統合（キー：department*urban*income）
# ******************************************************************************
# 食品群消費データの読み込み
df_food_consumption_org <- read_rds(file.path(gdrive_enaho_dir,
        "food_consumption_by_area_income.rds")) %>% 
  mutate(
    inc_quintile = labelled::to_factor(inc_quintile),
    ena_staple_legume = staple_legume_log1p,
    ena_vegetable = vegetable_log1p,
    ena_fruit = fruit_log1p,
    ena_dairy = dairy_log1p,
    ena_ASF = ASF_log1p,
    ena_oilfat = oilfat_log1p,
    enase_staple_legume = staple_legume_log1p_se,
    enase_vegetable = vegetable_log1p_se,
    enase_fruit = fruit_log1p_se,
    enase_dairy = dairy_log1p_se,
    enase_ASF = ASF_log1p_se,
    enase_oilfat = oilfat_log1p_se
    )


# マージ実行(dep, rural, incomeで結合)
all_data_merged <- all_data_merged %>%
  mutate(
    dm_income_quintile = case_when(
      v190 == 1 ~ "1",
      v190 == 2 ~ "2",
      v190 == 3 ~ "3",
      v190 == 4 ~ "4",
      v190 == 5 ~ "5",
      TRUE ~ NA_character_
      ) %>% as.factor()
  ) %>%
  left_join_safe(df_food_consumption_org, c("v024" = "department", 
          "dm_rural" = "dm_rural", "dm_income_quintile" = "inc_quintile"))


# ファイルをRDSで保存
saveRDS(all_data_merged, file = file.path(gdrive_dir, "output", 
        "all_data_merged.rds"))

```