---
title: "_10_3_filter_variables"
format: html
---


# 1. 必要データの読み込み
```{r}
library(dplyr)

rm(list = ls(all = TRUE))

# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）
source("_tool_SaveLabel.R")  # survey用関数群
source("_tool_paper.R")  # labelled → papeRのラベル形式に変換する関数)

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

df_dummied <- readRDS(
  file.path(gdrive_dir, "output","all_data_merged_dummy.rds")
) 


```

# 2. 統合変数の作成

```{r}

df_dummied <- df_dummied %>%
  mutate(
    rh_del_stay_less_1day = case_when(
      rh_del_stay_6_11_hours_yes == 1 | rh_del_stay_12_23_hours_yes == 1 ~ 1L, 
      rh_del_stay_Dont_know_missing_yes == 1 ~ NA_integer_,
      TRUE ~ 0L
      ),
    rh_del_facility_any = case_when(
      rh_del_place_Health_facility_yes == 1 ~ 1L,
      rh_del_place_Missing_yes == 1 ~ NA_integer_,
      TRUE ~ 0L
      ),
    dm_young_family = ifelse(dm_age_of_hh_head_10s_yes == 1 | dm_age_of_hh_head_20s_yes == 1, 1L, 0L),
    ph_wtr_far = ifelse(ph_wtr_time_More_than_30_minutes_yes == 1, 1L, 0L),
    ms_teen_preg = ifelse(ms_afm_15 == 1|ms_afm_18 == 1, 1L, 0L),
    nt_wm_micro_iron_appropriate = case_when(
      nt_wm_micro_iron_90__yes == 1 ~ 1L,
      nt_wm_micro_iron_Dont_know_missing_yes == 1 ~ NA_integer_,
      TRUE ~ 0L
    )
  )

  labels_new <- list(
    rh_del_stay_less_1day = "Delivery stay less than 1 day",
    rh_del_facility_any = "Delivery at any facility",
    dm_young_family = "Household head age 10s or 20s",
    ph_wtr_far = "Water source more than 30 minutes away",
    ms_teen_preg = "Teenage pregnancy",
    nt_wm_micro_iron_appropriate = "Appropriate micronutrient intake"
  )
  
  papeR::labels(df_dummied, which = names(labels_new)) <- unlist(labels_new, use.names = FALSE)
  

# ダミー変数化後のラベル情報一覧
  var_summary_dummied <- variable_summary(df_dummied)
  
  write.xlsx(
    var_summary_dummied,
    file = file.path(gdrive_dir, "output", "labels", "label_all_data_merged_dummy.xlsx"),
    sheetName = "main",
    rowNames = FALSE,
    na.string = "NA"
  )

```

