---
title: "10_2_merged_data_convert_to _dummy"
format: html
---


# 1. 必要データの読み込み
```{r}
library(dplyr)

rm(list = ls(all = TRUE))

# 各種の関数セット読み込み
source("../myTools.R")  # プロジェクトルートから読み込む（quarto限定の処理）
source("_tool_SaveLabel.R")  # survey用関数群

# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

df_org <- readRDS(
  file.path(gdrive_dir, "output","all_data_merged.rds")
) 

# 変数ラベルをメモリに保存したうえでラベル消去
labels_memory <- save_labels_to_memory(df_org)
df_org_plane <- remove_labels(df_org, remove_factor = FALSE)
saveRDS(labels_memory, file = file.path(gdrive_dir, "output", "labels", "labels_all_data_merged.rds"))

```

# 2. ダミー変数化

```{r}
library(fastDummies)

df_dummied <- df_org_plane

# ダミー化したい factor 変数を選ぶ
vars <- names(df_dummied)[sapply(df_dummied, is.factor)]

for (v in vars) {
  # v だけを対象に dummy_cols（行数はそのまま）
  _tmp_dummy <- dummy_cols(
    df_dummied[c(v)],
    remove_first_dummy = FALSE,
    ignore_na = FALSE,              # NA専用ダミー列も作る
    remove_selected_columns = TRUE
  )

  # v_NA 列を利用して、「元がNAの行では他レベルをNAにする」
  na_col   <- paste0(v, "_NA")
  lvl_cols <- grep(paste0("^", v, "_"), names(_tmp_dummy), value = TRUE)
  lvl_cols <- setdiff(lvl_cols, na_col)

  idx_na <- which(_tmp_dummy[[na_col]] == 1)
  _tmp_dummy[idx_na, lvl_cols] <- NA

  # v_NA 列を不要なら削除
  _tmp_dummy[[na_col]] <- NULL

  # 元の df_dummied から v を削除して、ダミー列を結合
  df_dummied[[v]] <- NULL
  df_dummied <- cbind(df_dummied, _tmp_dummy)
}


```

# 3. ダミー変数化後のデータに変数ラベルを付与

```{r}

dummy_labels <- list()

# 元のラベル情報を取得
var_labels <- labels_memory$var_labels
val_labels <-labels_memory$val_labels

for (v in vars) {
  # 変数ラベルを取得
  var_label <- var_labels[[v]]

  # 展開したダミー変数の列名(レベルの数だけ存在)を取得
  lvl_cols <- grep(paste0("^", v, "_"), names(df_dummied), value = TRUE)

  for (lvl_col in lvl_cols) {
    # レベル名を抽出
    lvl_name <- sub(paste0("^", v, "_"), "", lvl_col)

    # ラベルを作成
    if (lvl_name %in% names(val_labels)) {
      # 値ラベルが存在する場合
      lvl_label <- value_labels[[lvl_name]]
    } else if (lvl_name == "NA") {
      # NAレベルの場合
      lvl_label <- "Missing"
    } else {
      # 値ラベルが存在しない場合、そのままレベル名を使用
      lvl_label <- lvl_name
    }

    # 変数ラベルを設定
    full_label <- paste0(var_label, ": ", lvl_label)
    dummy_labels[[lvl_col]] <- full_label
  }
}

# 新ラベルをデータフレームに適用
new_label_set <- list(var_labels = dummy_labels, val_labels = list())
df_dummied <- restore_labels(df_dummied, new_label_set)

# 残りの旧ラベル（オリジナル）も復元
df_dummied <- restore_labels(df_dummied, labels_memory)

# 最終的なラベル一覧を保存
final_labels_memory <- save_labels_to_memory(df_dummied)
saveRDS(final_labels_memory, file = file.path(gdrive_dir, "output", "labels", "labels_all_data_merged_dummy.rds"))

# ダミー変数化後のデータ保存
saveRDS(df_dummied, file = file.path(gdrive_dir, "output","all_data_merged_dummy.rds"))


```