---
title: "_13_3_descriptive_stat"
format: html
---

## Descriptive Statistics
## 1. データ読み込み

```{r}
# ================================================================================
# 0. 初期設定・パッケージ読み込み
# ================================================================================
library(tinytex)
library(here)
library(haven)
library(labelled)
library(glmnet)
library(tidyverse)
# library(fastDummies)
library(nnet)      # 多項ロジスティック回帰
library(survey)    # 重み付き統計解析
library(sjlabelled)　# ラベル付きデータ処理用
library(tableone)
library(fixest)   # 回帰分析の推定結果から係数表（推定値、標準誤差、t値、p値など）を抽出

# オブジェクトクリア
rm(list = ls(all = TRUE))

# デバッグモードフラグ
debug_mode = TRUE  # デバッグモード
# debug_mode = FALSE # 通常モード

# 自作関数読み込み
source("../myTools.R")

# ================================================================================
# 1. データ読み込み
# ================================================================================
# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# 結果保存先
save_path <- file.path(gdrive_dir, "output", "lasso_IV01")

svydesign_org <-  readRDS(
    file.path(save_path, "svy_design_lasso_IV_org.rds")
  )



```
## 2. データ確認

```{r}
library(survey)
library(gtsummary)

#' ******************************************************************************
#' @title: create_gt
#' @description tbl_summaryオブジェクトからgtテーブルを作成する関数
#' @param tbl_summary_obj tbl_summaryオブジェクト
#' @param title_text タイトルテキスト
#' @param subtitle_text サブタイトルテキスト
#' @return gtテーブル
#' ******************************************************************************
create_gt <- function(tbl_summary_obj, title_text, subtitle_text) {
  result_df <- tbl_summary_obj %>%
    gt() %>%
    tab_header(
      title = title_text,
      subtitle = subtitle_text
    ) %>%
    fmt_number(
      columns = c(estimate, conf.low, conf.high),
      decimals = 2
    ) %>%
    fmt_number(
      columns = p.value,
      decimals = 3
    ) %>%
    cols_label(
      label_all = "Variable",
      estimate = "Odds Ratio",
      conf.low = "95% CI Low",
      conf.high = "95% CI High",
      p.value = "P-value"
    ) %>%
    tab_source_note(
    source_note = "Note: two separate descriptive statistics are shown based on food consumption variables(griup1) and food score variables(group2) to avoid possible multicolinearity."
  )

  return(result_df)
}
# ---- 関数ここまで ------------------------------------------------------------
library(survey)
library(gtsummary)

covariates <- c("nt_wm_ht", "ch_below_2p5", "dm_children_under12", "rc_edu", 
                "dm_sheep_own", "rh_anc_pvskill", "dm_refrigerator", 
                "nt_wm_ovobese", "ph_wtr_time", "dm_age_of_hh_head", 
                "dm_capital", "ph_sani_open", "dm_cooking_fuel_traditional", 
                "dm_weath_index", "rh_prob_permit", "ms_afm_15", 
                "ph_wtr_trt_cloth", "ch_stool_safe", "dm_dvjustify_onereas")

food_vars <- c("nt_grains", "nt_root", "nt_vita", "nt_frtveg", "nt_nuts", 
               "nt_meatfish", "nt_eggs", "nt_dairy", "nt_mdd", "nt_mmf")

food_score_vars <- c("staple_legume_log1p_score_ok", "vegetable_log1p_score_ok", 
                     "fruit_log1p_score_ok", "dairy_log1p_score_ok", 
                     "ASF_log1p_score_ok", "oilfat_log1p_score_ok")

outcome_var <- c("nt_ch_stunt", "nt_ch_wast", "nt_ch_any_anem")

dscriptive_stat_vars <- c(covariates, food_vars, outcome_var)

dstrat <- svydesign_org

dstrat$variables <- dstrat$variables %>%
  mutate(
    analysis_grp = case_when(
      treatment_group == 0 & year < 2009  ~ "control_early(<2009)",
      treatment_group == 0 & year >= 2009  ~ "control_late(>=2009)",
      treatment_group == 1 & year < 2009  ~ "ctreat_early_pre",
      treatment_group == 1 & year >= 2009  ~ "control_late_post",
      treatment_group == 2 & year < 2011  ~ "ctreat_early_pre",
      treatment_group == 2 & year >= 2011  ~ "control_late_post"
    )
  )

# 3. tbl_svysummaryで記述統計表を作成
dstrat %>%
  tbl_svysummary(
    by = analysis_grp,                  # グループ分け（任意）
    include = dscriptive_stat_vars,     # 集計したい変数
    statistic = list(all_continuous() ~ "{mean} ({sd})") # 統計量の指定
  ) %>%
  add_p() %>%     # 重み付けを考慮したp値を追加
  add_n() %>%     # サンプルサイズを追加
  bold_labels()

# ----------------------------------------------------------------------------
# 
# covariates <- c("nt_wm_ht", "ch_below_2p5", "dm_children_under12", "rc_edu", 
#                 "dm_sheep_own", "rh_anc_pvskill", "dm_refrigerator", 
#                 "nt_wm_ovobese", "ph_wtr_time", "dm_age_of_hh_head", 
#                 "dm_capital", "ph_sani_open", "dm_cooking_fuel_traditional", 
#                 "dm_weath_index", "rh_prob_permit", "ms_afm_15", 
#                 "ph_wtr_trt_cloth", "ch_stool_safe", "dm_dvjustify_onereas")
# 
# food_vars <- c("nt_grains", "nt_root", "nt_vita", "nt_frtveg", "nt_nuts", 
#                "nt_meatfish", "nt_eggs", "nt_dairy", "nt_mdd", "nt_mmf")
# 
# food_score_vars <- c("staple_legume_log1p_score_ok", "vegetable_log1p_score_ok", 
#                      "fruit_log1p_score_ok", "dairy_log1p_score_ok", 
#                      "ASF_log1p_score_ok", "oilfat_log1p_score_ok")
# 
# 
# # 線形回帰モデル1（有意性記号付き）
# formula_str <- as.formula(
#   paste("nt_ch_stunt", " ~", paste(c(covariates, food_vars), collapse = " + ")))
# fit1 <- svyglm(formula_str, design = svydesign_org, family = binomial())
# 
# glm_res1_org <- fit1 %>% 
#   tbl_regression(exponentiate = TRUE) %>%
#   add_significance_stars(
#     hide_p = FALSE,
#     pattern = "{p.value}{stars}"
#   ) %>% as_gt() %>% as.data.frame() %>%
#   mutate(
#     label_all = case_when(
#       var_label == label ~ var_label,
#       TRUE ~ paste0(var_label, " (", gsub("^[\u00A0]+", "", label), ")")),
#     conf.low.org = strsplit(conf.low, ", ")
#   ) %>%
#   mutate(
#     label_all = case_when(
#       variable == "nt_grains" ~ "Grains consumed",
#       variable == "nt_root" ~ "Roots and tubers consumed",
#       variable == "nt_nuts" ~ "Nuts and seeds consumed",
#       variable == "nt_vita" ~ "Vitamin A-rich fruits and vegetables consumed",
#       variable == "nt_frtveg" ~ "Other fruits and vegetables consumed",
#       variable == "nt_meatfish" ~ "Meat, fish and poultry consumed",
#       variable == "nt_eggs" ~ "Eggs consumed",
#       variable == "nt_dairy" ~ "Dairy products consumed",
#       variable == "nt_mdd" ~ "Minimum dietary diversity",
#       variable == "nt_mmf" ~ "Minimum meal frequency",
#       variable == "staple_legume_log1p_score_ok" ~ "Staple and Legume score",
#       variable == "vegetable_log1p_score_ok" ~ "Vegetable score",
#       variable == "fruit_log1p_score_ok" ~ "Fruit score",
#       variable == "dairy_log1p_score_ok" ~ "Dairy score",
#       variable == "ASF_log1p_score_ok" ~ "Animal source food score",
#       variable == "oilfat_log1p_score_ok" ~ "Oil and fat score",
#       TRUE ~ label_all
#       )
#   ) %>%
#   mutate(
#     conf.low = map_chr(conf.low.org, 1),
#   ) %>% 
#   select(-conf.low.org)
#   
# 
# glm_res1 <- glm_res1_org %>%
#   select(label_all, N_obs, estimate, conf.low, conf.high, p.value) %>%
#   create_gt(
#     title_text = "Table: desccriptive stat - Group1(food consumption dummy)",
#     subtitle_text = "summary with All Variables"
#   )
# 
# 
# glm_compact_res1 <- glm_res1_org %>% 
#   filter(!stars == "") %>%
#   select(label_all, N_obs, estimate, conf.low, conf.high, p.value) %>%
#   create_gt(
#     title_text = "Table: desccriptive stat - Group2(food consumption dummy)",
#     subtitle_text = "summary with Significant Variables only"
#   )
# 
# glm_compact_res1
# gtsave(glm_res1, file.path(save_path, "descriptive_food_dummy.html"))
# gtsave(glm_compact_res1, file.path(save_path, "descriptive_food_dummy_compact.html"))
# 
# # 線形回帰モデル2（有意性記号付き）
# formula_str <- as.formula(
#   paste("nt_ch_stunt", " ~", paste(c(covariates, food_score_vars), collapse = " + ")))
# fit2 <- svyglm(formula_str, design = svydesign_org, family = binomial())
# 
# glm_res2_org <- fit2 %>% 
#   tbl_regression(exponentiate = TRUE) %>%
#   add_significance_stars(
#     hide_p = FALSE,
#     pattern = "{p.value}{stars}"
#   ) %>% as_gt() %>% as.data.frame() %>%
#   mutate(
#     label_all = case_when(
#       var_label == label ~ var_label,
#       TRUE ~ paste0(var_label, " (", gsub("^[\u00A0]+", "", label), ")")),
#     conf.low.org = strsplit(conf.low, ", ")
#   ) %>%
#   mutate(
#     label_all = case_when(
#       variable == "nt_grains" ~ "Grains consumed",
#       variable == "nt_root" ~ "Roots and tubers consumed",
#       variable == "nt_nuts" ~ "Nuts and seeds consumed",
#       variable == "nt_vita" ~ "Vitamin A-rich fruits and vegetables consumed",
#       variable == "nt_frtveg" ~ "Other fruits and vegetables consumed",
#       variable == "nt_meatfish" ~ "Meat, fish and poultry consumed",
#       variable == "nt_eggs" ~ "Eggs consumed",
#       variable == "nt_dairy" ~ "Dairy products consumed",
#       variable == "nt_mdd" ~ "Minimum dietary diversity",
#       variable == "nt_mmf" ~ "Minimum meal frequency",
#       variable == "staple_legume_log1p_score_ok" ~ "Staple and Legume score",
#       variable == "vegetable_log1p_score_ok" ~ "Vegetable score",
#       variable == "fruit_log1p_score_ok" ~ "Fruit score",
#       variable == "dairy_log1p_score_ok" ~ "Dairy score",
#       variable == "ASF_log1p_score_ok" ~ "Animal source food score",
#       variable == "oilfat_log1p_score_ok" ~ "Oil and fat score",
#       TRUE ~ label_all
#       )
#   ) %>%
#   mutate(
#     conf.low = map_chr(conf.low.org, 1),
#   ) %>% 
#   select(-conf.low.org)
#  
# 
# glm_res2 <- glm_res2_org %>%
#   select(label_all, N_obs, estimate, conf.low, conf.high, p.value) %>%
#   create_gt(
#     title_text = "Table: desccriptive stat - Group1(food score dummy)",
#     subtitle_text = "summary with All Variables"
#   )
# 
# glm_compact_res2 <- glm_res2_org %>%
#   filter(!stars == "") %>%
#   select(label_all, N_obs, estimate, conf.low, conf.high, p.value) %>%
#   create_gt(
#     title_text = "Table: desccriptive stat - Group1(food score dummy)",
#     subtitle_text = "summary with Significant Variables only"
#   )
# 
# glm_compact_res2
# 
# gtsave(glm_res2, file.path(save_path, "descriptive_food_score.html"))
# gtsave(glm_compact_res2, file.path(save_path, "descriptive_food_score_compact.html"))

```
