---
title: "_13_3_descriptive_stat"
format: html
---

## Descriptive Statistics
## 1. データ読み込み

```{r}
# ================================================================================
# 0. 初期設定・パッケージ読み込み
# ================================================================================
library(tinytex)
library(here)
library(haven)
library(labelled)
library(glmnet)
library(tidyverse)
# library(fastDummies)
library(nnet)      # 多項ロジスティック回帰
library(survey)    # 重み付き統計解析
library(sjlabelled)　# ラベル付きデータ処理用
library(tableone)
library(fixest)   # 回帰分析の推定結果から係数表（推定値、標準誤差、t値、p値など）を抽出

# オブジェクトクリア
rm(list = ls(all = TRUE))

# デバッグモードフラグ
debug_mode = TRUE  # デバッグモード
# debug_mode = FALSE # 通常モード

# 自作関数読み込み
source("../myTools.R")

# ================================================================================
# 1. データ読み込み
# ================================================================================
# DHSデータのルートフォルダを指定
gdrive_dir <- "/Users/snakada/Library/CloudStorage/GoogleDrive-snakada@g.ecc.u-tokyo.ac.jp/マイドライブ/Peru_work/Peru_endes/spss"

# 結果保存先
save_path <- file.path(gdrive_dir, "output", "lasso_IV01")

svydesign_org <-  readRDS(
    file.path(save_path, "svy_design_lasso_org.rds")
  )



```
## 2. データ確認

```{r}
library(survey)
library(gtsummary)


options(survey.lonely.psu = "adjust")

covariates <- c("nt_wm_ht", "ch_below_2p5", "dm_child_more_than3", "rc_edu_secondary", 
                "dm_sheeep_own", "rh_anc_pvskill", "dm_refrigerator", 
                "nt_wm_ovobese", "ph_wtr_far", "dm_hh_head_30plus", 
                "dm_city", "dm_sani_open_yes", "dm_cooking_fuel_traditional", 
                "dm_weath_index", "rh_prob_permit", "ms_afm_15", 
                "ph_wtr_trt_cloth", "ch_stool_safe_no", "dm_dvjustify_onereas")

food_vars <- c("nt_grains", "nt_root", "nt_vita", "nt_frtveg", "nt_nuts", 
               "nt_meatfish", "nt_eggs", "nt_dairy", "nt_mdd", "nt_mmf")

food_score_vars <- c("staple_legume_log1p_score_ok", "vegetable_log1p_score_ok", 
                     "fruit_log1p_score_ok", "dairy_log1p_score_ok", 
                     "ASF_log1p_score_ok", "oilfat_log1p_score_ok")

outcome_var <- c("nt_ch_stunt", "nt_ch_wast", "nt_ch_any_anem")

dscriptive_stat_vars <- c(covariates, food_vars, outcome_var)

style_p_star <- function(p) {
  dplyr::case_when(
    p < 0.001 ~ "***",
    p < 0.01  ~ "**",
    p < 0.05  ~ "*",
    TRUE      ~ ""
  )
}

dstrat <- svydesign_org

dstrat$variables <- dstrat$variables %>%
  mutate(
    analysis_grp = case_when(
      treatment_group == 0 & year < 2009  ~ "control_pre(<2009)",
      treatment_group == 0 & year >= 2009  ~ "control_post(>=2009)",
      treatment_group == 1 & year < 2009  ~ "treat_pre",
      treatment_group == 1 & year >= 2009  ~ "treat_post",
      treatment_group == 2 & year < 2011  ~ "treat_pre",
      treatment_group == 2 & year >= 2011  ~ "treat_post"
    )
  ) %>% 
  mutate(
    analysis_grp = factor(analysis_grp, 
                          levels =c("control_pre(<2009)", "treat_pre",
                                    "control_post(>=2009)", "treat_post"))  
  )%>% 
  mutate(
    dm_child_more_than3 = ifelse(dm_children_under12 > 3, 1, 0),
    rc_edu_secondary = case_when(
      rc_edu %in% c("Complete secondary", "Higher") ~ 1,
      TRUE ~ 0
      ),
    dm_sheeep_own = ifelse(dm_sheep_own == "Yes (owns sheep)", 1, 0),
    ph_wtr_far = ifelse(ph_wtr_time %in% c("More than 30 minutes"), 1, 0),
    dm_hh_head_30plus = ifelse(dm_age_of_hh_head %in% c("10s", "20s"), 0, 1),
    dm_sani_open_yes = ifelse(ph_sani_open %in% c("open defecation"), 1, 0),
    ch_stool_safe_no = ifelse(ch_stool_safe %in% c("Not safe"), 1, 0),
  ) %>%
  set_variable_labels(
      dm_child_more_than3 = "more than 3 child under 12",
      rc_edu_secondary = "secondary or higher education",
      dm_sheeep_own = "own a sheep",
      ph_wtr_far = "water fetching over 30min",
      dm_hh_head_30plus = "HH head over 29",
      dm_sani_open_yes = "open defication",
      ch_stool_safe_no = "stool improper handling"
    )

# subsetの前にラベルを保存
var_labels_list <- var_label(dstrat$variables)

# サブセット作成
design_pre <- subset(dstrat, analysis_grp %in% c("control_pre(<2009)", "treat_pre"))
design_pre$variables$analysis_grp <- droplevels(design_pre$variables$analysis_grp)

design_post <- subset(dstrat, analysis_grp %in% c("control_post(>=2009)", "treat_post"))
design_post$variables$analysis_grp <- droplevels(design_post$variables$analysis_grp)

# サブセット後にラベルを復元
var_label(design_pre$variables) <- var_labels_list
var_label(design_post$variables) <- var_labels_list

# 3. tbl_svysummaryで記述統計表を作成
get_summary <- function(design_obj, covariates, grp_var) {
  res <- design_obj %>%
    tbl_svysummary(
      by = analysis_grp,                  # グループ分け（任意）
      include = dscriptive_stat_vars,     # 集計したい変数
      statistic = list(all_continuous() ~ "{mean} ({sd})") # 統計量の指定
    ) %>%
    add_p(
      test = list(
        all_continuous()  ~ "svy.t.test",
        all_categorical() ~ "svy.wald.test"
      )
    ) %>%     # 重み付けを考慮したp値を追加
    # ★ ここで p.value から星を抽出して、stat 列に追記
    modify_table_body(
      ~ .x |>
        mutate(
          across(
            starts_with("stat_2"),
            ~ case_when(
              !is.na(p.value) & p.value < 0.001 ~
                paste0(., " ***"),
              !is.na(p.value) & p.value < 0.01  ~
                paste0(., " **"),
              !is.na(p.value) & p.value < 0.05  ~
                paste0(., " *"),
              TRUE ~ .
            ),
            .names = "{.col}"
          )
        )
    ) |>
    # p.value 列を隠す
    modify_table_styling(
      columns = "p.value",
      hide    = TRUE
    ) |>
    add_n() %>%     # サンプルサイズを追加
    bold_labels()

  return(res)
}


result1 <- get_summary(design_pre, dscriptive_stat_vars, analysis_grp)
result2 <- get_summary(design_post, dscriptive_stat_vars, analysis_grp)

# 結果保存
saveRDS(result1, file.path(save_path, "descriptive_stat_pre.rds"))
saveRDS(result2, file.path(save_path, "descriptive_stat_post.rds"))


```
